TASKS_FILENAME: tasks # имя файла для сохранения заданий
ANSWERS_FILENAME: ans # имя файла для сохранения ответов
TASKS_AMOUNT: 3 # количество задач для генерации
TASK_DESCRIPTION: 'Робот стартовал в месте траектории, отмеченным жирной точкой,
и оставил за собой след. У робота есть всего 5 команд. Команда представляет из
себя короткий фрагмент траектории. Начало отмечено жирной точкой. Каждая команда
может быть повёрнута в плоскости, но не отражена зеркально.
Задача: придумайте наиболее короткую последовательность команд, которую мог
выполнить робот, чтобы получилась траектория, изображенная ниже.
Траектории обозначаются буквами A, B, C...' # описание задания
CELLSIZE: 20  # сторона клетки
TRAJECTORY_LENGTH: 5  # длина команды робота
TRAJECTORY_AMOUNT: 4  # количество команд робота
DIFFICULTY: 3 # сложность задания
CELLS: False # рисовать ли клетки?

WINDOW_WIDTH: 1920  # ширина и высота окна
WINDOW_HEIGHT: 1080
TRAJECTORY_STEP: 10  # отступ между траекториями
TASK_START_POINT_X: 10 # координаты начала задания
TASK_START_POINT_Y: 15
